# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_editor.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dataEditor(object):
    def setupUi(self, dataEditor):
        dataEditor.setObjectName("dataEditor")
        dataEditor.resize(735, 552)
        dataEditor.setStyleSheet("QSplitter::handle { border: 2px outset darkgrey; }")
        dataEditor.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(dataEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.dataColumnView = QtWidgets.QColumnView(self.splitter)
        self.dataColumnView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dataColumnView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.dataColumnView.setDragEnabled(True)
        self.dataColumnView.setDragDropOverwriteMode(True)
        self.dataColumnView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.dataColumnView.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.dataColumnView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.dataColumnView.setObjectName("dataColumnView")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.nameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout_4.addWidget(self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.nameLineEdit.setReadOnly(True)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.horizontalLayout_4.addWidget(self.nameLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.empty = QtWidgets.QWidget()
        self.empty.setObjectName("empty")
        self.stackedWidget.addWidget(self.empty)
        self.descriptionPage = QtWidgets.QWidget()
        self.descriptionPage.setObjectName("descriptionPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.descriptionPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.descriptionPage)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.descriptionTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.descriptionTextEdit.setEnabled(True)
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.verticalLayout_8.addWidget(self.descriptionTextEdit)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.stackedWidget.addWidget(self.descriptionPage)
        self.iconPage = QtWidgets.QWidget()
        self.iconPage.setObjectName("iconPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.iconPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadIconButton = QtWidgets.QPushButton(self.iconPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadIconButton.sizePolicy().hasHeightForWidth())
        self.loadIconButton.setSizePolicy(sizePolicy)
        self.loadIconButton.setObjectName("loadIconButton")
        self.horizontalLayout_3.addWidget(self.loadIconButton)
        self.iconLabel = QtWidgets.QLabel(self.iconPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconLabel.sizePolicy().hasHeightForWidth())
        self.iconLabel.setSizePolicy(sizePolicy)
        self.iconLabel.setMaximumSize(QtCore.QSize(40, 40))
        self.iconLabel.setText("")
        self.iconLabel.setPixmap(QtGui.QPixmap(":/icons/image-32.png"))
        self.iconLabel.setObjectName("iconLabel")
        self.horizontalLayout_3.addWidget(self.iconLabel)
        self.deleteIconButton = QtWidgets.QPushButton(self.iconPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteIconButton.sizePolicy().hasHeightForWidth())
        self.deleteIconButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteIconButton.setIcon(icon)
        self.deleteIconButton.setObjectName("deleteIconButton")
        self.horizontalLayout_3.addWidget(self.deleteIconButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.iconPage)
        self.ingredientUnit = QtWidgets.QWidget()
        self.ingredientUnit.setObjectName("ingredientUnit")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.ingredientUnit)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.factorLabel = QtWidgets.QLabel(self.ingredientUnit)
        self.factorLabel.setObjectName("factorLabel")
        self.gridLayout.addWidget(self.factorLabel, 1, 0, 1, 1)
        self.unitLabel = QtWidgets.QLabel(self.ingredientUnit)
        self.unitLabel.setObjectName("unitLabel")
        self.gridLayout.addWidget(self.unitLabel, 0, 0, 1, 1)
        self.factorLineEdit = QtWidgets.QLineEdit(self.ingredientUnit)
        self.factorLineEdit.setObjectName("factorLineEdit")
        self.gridLayout.addWidget(self.factorLineEdit, 1, 1, 1, 1)
        self.baseUnitLabel = QtWidgets.QLabel(self.ingredientUnit)
        self.baseUnitLabel.setText("Base unit")
        self.baseUnitLabel.setObjectName("baseUnitLabel")
        self.gridLayout.addWidget(self.baseUnitLabel, 1, 2, 1, 1)
        self.typeComboBox = QtWidgets.QComboBox(self.ingredientUnit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeComboBox.sizePolicy().hasHeightForWidth())
        self.typeComboBox.setSizePolicy(sizePolicy)
        self.typeComboBox.setEditable(False)
        self.typeComboBox.setObjectName("typeComboBox")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/sum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.typeComboBox.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/weight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.typeComboBox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/beaker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.typeComboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/paper-bag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.typeComboBox.addItem(icon4, "")
        self.gridLayout.addWidget(self.typeComboBox, 0, 1, 1, 2)
        self.verticalLayout_9.addLayout(self.gridLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.ingredientUnit)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.unitDescriptionTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.unitDescriptionTextEdit.setObjectName("unitDescriptionTextEdit")
        self.verticalLayout_7.addWidget(self.unitDescriptionTextEdit)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.stackedWidget.addWidget(self.ingredientUnit)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.okButton = QtWidgets.QPushButton(self.layoutWidget)
        self.okButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okButton.setIcon(icon5)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_2.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setIcon(icon)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.massRadioButton = QtWidgets.QRadioButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.massRadioButton.sizePolicy().hasHeightForWidth())
        self.massRadioButton.setSizePolicy(sizePolicy)
        self.massRadioButton.setIcon(icon2)
        self.massRadioButton.setChecked(True)
        self.massRadioButton.setObjectName("massRadioButton")
        self.unitButtonGroup = QtWidgets.QButtonGroup(dataEditor)
        self.unitButtonGroup.setObjectName("unitButtonGroup")
        self.unitButtonGroup.addButton(self.massRadioButton)
        self.horizontalLayout.addWidget(self.massRadioButton)
        self.volumeRadioButton = QtWidgets.QRadioButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeRadioButton.sizePolicy().hasHeightForWidth())
        self.volumeRadioButton.setSizePolicy(sizePolicy)
        self.volumeRadioButton.setIcon(icon3)
        self.volumeRadioButton.setObjectName("volumeRadioButton")
        self.unitButtonGroup.addButton(self.volumeRadioButton)
        self.horizontalLayout.addWidget(self.volumeRadioButton)
        self.quantityRadioButton = QtWidgets.QRadioButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantityRadioButton.sizePolicy().hasHeightForWidth())
        self.quantityRadioButton.setSizePolicy(sizePolicy)
        self.quantityRadioButton.setIcon(icon1)
        self.quantityRadioButton.setObjectName("quantityRadioButton")
        self.unitButtonGroup.addButton(self.quantityRadioButton)
        self.horizontalLayout.addWidget(self.quantityRadioButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.unitConversionTableView = QtWidgets.QTableView(self.tab_2)
        self.unitConversionTableView.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.unitConversionTableView.setObjectName("unitConversionTableView")
        self.verticalLayout_4.addWidget(self.unitConversionTableView)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        dataEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dataEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 30))
        self.menubar.setObjectName("menubar")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        dataEditor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dataEditor)
        self.statusbar.setObjectName("statusbar")
        dataEditor.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(dataEditor)
        self.toolBar.setObjectName("toolBar")
        dataEditor.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave = QtWidgets.QAction(dataEditor)
        self.actionSave.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon6)
        self.actionSave.setObjectName("actionSave")
        self.actionRevert = QtWidgets.QAction(dataEditor)
        self.actionRevert.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/arrow-return-180-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRevert.setIcon(icon7)
        self.actionRevert.setObjectName("actionRevert")
        self.actionDelete = QtWidgets.QAction(dataEditor)
        self.actionDelete.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon8)
        self.actionDelete.setObjectName("actionDelete")
        self.menuData.addAction(self.actionSave)
        self.menuData.addAction(self.actionRevert)
        self.menubar.addAction(self.menuData.menuAction())
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionRevert)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDelete)

        self.retranslateUi(dataEditor)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dataEditor)

    def retranslateUi(self, dataEditor):
        _translate = QtCore.QCoreApplication.translate
        dataEditor.setWindowTitle(_translate("dataEditor", "Data Editor"))
        self.nameLabel.setText(_translate("dataEditor", "Name:"))
        self.groupBox.setTitle(_translate("dataEditor", "Description"))
        self.loadIconButton.setText(_translate("dataEditor", "Load Icon:"))
        self.deleteIconButton.setText(_translate("dataEditor", "Delete"))
        self.factorLabel.setText(_translate("dataEditor", "Factor"))
        self.unitLabel.setText(_translate("dataEditor", "Type"))
        self.typeComboBox.setItemText(0, _translate("dataEditor", "Quantity"))
        self.typeComboBox.setItemText(1, _translate("dataEditor", "Mass"))
        self.typeComboBox.setItemText(2, _translate("dataEditor", "Volume"))
        self.typeComboBox.setItemText(3, _translate("dataEditor", "Unspecific"))
        self.groupBox_2.setTitle(_translate("dataEditor", "Description"))
        self.okButton.setText(_translate("dataEditor", "OK"))
        self.cancelButton.setText(_translate("dataEditor", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("dataEditor", "Items"))
        self.massRadioButton.setText(_translate("dataEditor", "Mass"))
        self.volumeRadioButton.setText(_translate("dataEditor", "Volume"))
        self.quantityRadioButton.setText(_translate("dataEditor", "Quantity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("dataEditor", "Unit Conversion Table"))
        self.menuData.setTitle(_translate("dataEditor", "Data"))
        self.toolBar.setWindowTitle(_translate("dataEditor", "toolBar"))
        self.actionSave.setText(_translate("dataEditor", "Save"))
        self.actionRevert.setText(_translate("dataEditor", "Revert"))
        self.actionDelete.setText(_translate("dataEditor", "Delete"))
from qisit.qt.resources import resources_rc
