# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_editor.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dataEditor(object):
    def setupUi(self, dataEditor):
        dataEditor.setObjectName("dataEditor")
        dataEditor.resize(735, 552)
        dataEditor.setStyleSheet("QSplitter::handle { border: 2px outset darkgrey; }")
        dataEditor.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(dataEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.dataColumnView = QtWidgets.QColumnView(self.splitter)
        self.dataColumnView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dataColumnView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.dataColumnView.setDragEnabled(True)
        self.dataColumnView.setDragDropOverwriteMode(True)
        self.dataColumnView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.dataColumnView.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.dataColumnView.setObjectName("dataColumnView")
        self.stackedWidget = QtWidgets.QStackedWidget(self.splitter)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.massRadioButton = QtWidgets.QRadioButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.massRadioButton.sizePolicy().hasHeightForWidth())
        self.massRadioButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/weight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.massRadioButton.setIcon(icon)
        self.massRadioButton.setChecked(True)
        self.massRadioButton.setObjectName("massRadioButton")
        self.unitButtonGroup = QtWidgets.QButtonGroup(dataEditor)
        self.unitButtonGroup.setObjectName("unitButtonGroup")
        self.unitButtonGroup.addButton(self.massRadioButton)
        self.horizontalLayout.addWidget(self.massRadioButton)
        self.volumeRadioButton = QtWidgets.QRadioButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeRadioButton.sizePolicy().hasHeightForWidth())
        self.volumeRadioButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/beaker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.volumeRadioButton.setIcon(icon1)
        self.volumeRadioButton.setObjectName("volumeRadioButton")
        self.unitButtonGroup.addButton(self.volumeRadioButton)
        self.horizontalLayout.addWidget(self.volumeRadioButton)
        self.quantityRadioButton = QtWidgets.QRadioButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantityRadioButton.sizePolicy().hasHeightForWidth())
        self.quantityRadioButton.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/sum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quantityRadioButton.setIcon(icon2)
        self.quantityRadioButton.setObjectName("quantityRadioButton")
        self.unitButtonGroup.addButton(self.quantityRadioButton)
        self.horizontalLayout.addWidget(self.quantityRadioButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.unitConversionTableView = QtWidgets.QTableView(self.tab_2)
        self.unitConversionTableView.setObjectName("unitConversionTableView")
        self.verticalLayout_4.addWidget(self.unitConversionTableView)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        dataEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dataEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 30))
        self.menubar.setObjectName("menubar")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        dataEditor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dataEditor)
        self.statusbar.setObjectName("statusbar")
        dataEditor.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(dataEditor)
        self.toolBar.setObjectName("toolBar")
        dataEditor.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave = QtWidgets.QAction(dataEditor)
        self.actionSave.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionRevert = QtWidgets.QAction(dataEditor)
        self.actionRevert.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/arrow-return-180-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRevert.setIcon(icon4)
        self.actionRevert.setObjectName("actionRevert")
        self.actionDelete = QtWidgets.QAction(dataEditor)
        self.actionDelete.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon5)
        self.actionDelete.setObjectName("actionDelete")
        self.menuData.addAction(self.actionSave)
        self.menuData.addAction(self.actionRevert)
        self.menubar.addAction(self.menuData.menuAction())
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionRevert)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDelete)

        self.retranslateUi(dataEditor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dataEditor)

    def retranslateUi(self, dataEditor):
        _translate = QtCore.QCoreApplication.translate
        dataEditor.setWindowTitle(_translate("dataEditor", "Data Editor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("dataEditor", "Items"))
        self.massRadioButton.setText(_translate("dataEditor", "Mass"))
        self.volumeRadioButton.setText(_translate("dataEditor", "Volume"))
        self.quantityRadioButton.setText(_translate("dataEditor", "Quantity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("dataEditor", "Unit Conversion Table"))
        self.menuData.setTitle(_translate("dataEditor", "Data"))
        self.toolBar.setWindowTitle(_translate("dataEditor", "toolBar"))
        self.actionSave.setText(_translate("dataEditor", "Save"))
        self.actionRevert.setText(_translate("dataEditor", "Revert"))
        self.actionDelete.setText(_translate("dataEditor", "Delete"))
from qisit.qt.resources import resources_rc
