# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recipe.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecipeWindow(object):
    def setupUi(self, RecipeWindow):
        RecipeWindow.setObjectName("RecipeWindow")
        RecipeWindow.resize(1062, 973)
        RecipeWindow.setWindowTitle("<Recipe Window>")
        RecipeWindow.setStyleSheet("QSplitter::handle { border: 2px outset darkgrey; }")
        RecipeWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        RecipeWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(RecipeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.recipeTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.recipeTitleLabel.setObjectName("recipeTitleLabel")
        self.horizontalLayout.addWidget(self.recipeTitleLabel)
        self.recipeTitleLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.recipeTitleLineEdit.setEnabled(True)
        self.recipeTitleLineEdit.setInputMask("")
        self.recipeTitleLineEdit.setText("")
        self.recipeTitleLineEdit.setReadOnly(False)
        self.recipeTitleLineEdit.setClearButtonEnabled(True)
        self.recipeTitleLineEdit.setObjectName("recipeTitleLineEdit")
        self.horizontalLayout.addWidget(self.recipeTitleLineEdit)
        self.calculateAmountButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateAmountButton.setEnabled(False)
        self.calculateAmountButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.calculateAmountButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calculateAmountButton.setIcon(icon)
        self.calculateAmountButton.setCheckable(True)
        self.calculateAmountButton.setObjectName("calculateAmountButton")
        self.horizontalLayout.addWidget(self.calculateAmountButton)
        self.calculateAmountDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.calculateAmountDoubleSpinBox.setSuffix("")
        self.calculateAmountDoubleSpinBox.setDecimals(1)
        self.calculateAmountDoubleSpinBox.setMinimum(0.5)
        self.calculateAmountDoubleSpinBox.setMaximum(9999.0)
        self.calculateAmountDoubleSpinBox.setSingleStep(0.5)
        self.calculateAmountDoubleSpinBox.setObjectName("calculateAmountDoubleSpinBox")
        self.horizontalLayout.addWidget(self.calculateAmountDoubleSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.mainSplitter = QtWidgets.QSplitter(self.centralwidget)
        self.mainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mainSplitter.setObjectName("mainSplitter")
        self.mainTabWidget = QtWidgets.QTabWidget(self.mainSplitter)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mainTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.imageSplitter = QtWidgets.QSplitter(self.mainTab)
        self.imageSplitter.setOrientation(QtCore.Qt.Vertical)
        self.imageSplitter.setObjectName("imageSplitter")
        self.layoutWidget = QtWidgets.QWidget(self.imageSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.imageHorizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.imageHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.imageHorizontalLayout.setObjectName("imageHorizontalLayout")
        self.imageLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setMinimumSize(QtCore.QSize(160, 120))
        self.imageLabel.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.imageLabel.setFont(font)
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap(":/icons/image-32.png"))
        self.imageLabel.setScaledContents(False)
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.imageHorizontalLayout.addWidget(self.imageLabel)
        self.imageListVerticalLayout = QtWidgets.QVBoxLayout()
        self.imageListVerticalLayout.setObjectName("imageListVerticalLayout")
        self.imageButtonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.imageButtonsHorizontalLayout.setObjectName("imageButtonsHorizontalLayout")
        self.addImagesButton = QtWidgets.QPushButton(self.layoutWidget)
        self.addImagesButton.setEnabled(True)
        self.addImagesButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addImagesButton.setIcon(icon1)
        self.addImagesButton.setObjectName("addImagesButton")
        self.imageButtonsHorizontalLayout.addWidget(self.addImagesButton)
        self.deleteImagesButton = QtWidgets.QPushButton(self.layoutWidget)
        self.deleteImagesButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteImagesButton.sizePolicy().hasHeightForWidth())
        self.deleteImagesButton.setSizePolicy(sizePolicy)
        self.deleteImagesButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteImagesButton.setIcon(icon2)
        self.deleteImagesButton.setObjectName("deleteImagesButton")
        self.imageButtonsHorizontalLayout.addWidget(self.deleteImagesButton)
        self.imageListVerticalLayout.addLayout(self.imageButtonsHorizontalLayout)
        self.imageTableView = QtWidgets.QTableView(self.layoutWidget)
        self.imageTableView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.imageTableView.setAcceptDrops(True)
        self.imageTableView.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.imageTableView.setDragEnabled(True)
        self.imageTableView.setDragDropOverwriteMode(False)
        self.imageTableView.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.imageTableView.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.imageTableView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.imageTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.imageTableView.setGridStyle(QtCore.Qt.NoPen)
        self.imageTableView.setCornerButtonEnabled(False)
        self.imageTableView.setObjectName("imageTableView")
        self.imageTableView.horizontalHeader().setVisible(True)
        self.imageTableView.horizontalHeader().setStretchLastSection(True)
        self.imageListVerticalLayout.addWidget(self.imageTableView)
        self.imageHorizontalLayout.addLayout(self.imageListVerticalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.imageSplitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.lastCookedDateEdit = QtWidgets.QDateEdit(self.layoutWidget1)
        self.lastCookedDateEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastCookedDateEdit.sizePolicy().hasHeightForWidth())
        self.lastCookedDateEdit.setSizePolicy(sizePolicy)
        self.lastCookedDateEdit.setReadOnly(False)
        self.lastCookedDateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(9999, 12, 28), QtCore.QTime(23, 59, 59)))
        self.lastCookedDateEdit.setCalendarPopup(True)
        self.lastCookedDateEdit.setObjectName("lastCookedDateEdit")
        self.gridLayout.addWidget(self.lastCookedDateEdit, 8, 2, 1, 2)
        self.neverCookedCheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.neverCookedCheckBox.setEnabled(True)
        self.neverCookedCheckBox.setObjectName("neverCookedCheckBox")
        self.gridLayout.addWidget(self.neverCookedCheckBox, 8, 4, 1, 1)
        self.catgoriesButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.catgoriesButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.catgoriesButton.setObjectName("catgoriesButton")
        self.gridLayout.addWidget(self.catgoriesButton, 0, 1, 1, 1)
        self.yieldsDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.yieldsDoubleSpinBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yieldsDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.yieldsDoubleSpinBox.setSizePolicy(sizePolicy)
        self.yieldsDoubleSpinBox.setReadOnly(False)
        self.yieldsDoubleSpinBox.setPrefix("")
        self.yieldsDoubleSpinBox.setDecimals(1)
        self.yieldsDoubleSpinBox.setMinimum(0.0)
        self.yieldsDoubleSpinBox.setMaximum(9999.0)
        self.yieldsDoubleSpinBox.setObjectName("yieldsDoubleSpinBox")
        self.gridLayout.addWidget(self.yieldsDoubleSpinBox, 2, 2, 1, 1)
        self.cuisineLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.cuisineLabel.setObjectName("cuisineLabel")
        self.gridLayout.addWidget(self.cuisineLabel, 3, 1, 1, 1)
        self.lastCookedLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.lastCookedLabel.setObjectName("lastCookedLabel")
        self.gridLayout.addWidget(self.lastCookedLabel, 8, 1, 1, 1)
        self.imageYieldsLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.imageYieldsLabel.setText("")
        self.imageYieldsLabel.setPixmap(QtGui.QPixmap(":/icons/plates.png"))
        self.imageYieldsLabel.setObjectName("imageYieldsLabel")
        self.gridLayout.addWidget(self.imageYieldsLabel, 2, 0, 1, 1)
        self.ratingLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.ratingLabel.setObjectName("ratingLabel")
        self.gridLayout.addWidget(self.ratingLabel, 1, 1, 1, 1)
        self.imagePreparationTimeLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.imagePreparationTimeLabel.setText("")
        self.imagePreparationTimeLabel.setPixmap(QtGui.QPixmap(":/icons/clock.png"))
        self.imagePreparationTimeLabel.setObjectName("imagePreparationTimeLabel")
        self.gridLayout.addWidget(self.imagePreparationTimeLabel, 5, 0, 1, 1)
        self.imageCookingTimeLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.imageCookingTimeLabel.setText("")
        self.imageCookingTimeLabel.setPixmap(QtGui.QPixmap(":/icons/clock.png"))
        self.imageCookingTimeLabel.setObjectName("imageCookingTimeLabel")
        self.gridLayout.addWidget(self.imageCookingTimeLabel, 6, 0, 1, 1)
        self.cookingTimeLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.cookingTimeLabel.setObjectName("cookingTimeLabel")
        self.gridLayout.addWidget(self.cookingTimeLabel, 6, 1, 1, 1)
        self.convertYieldsCheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.convertYieldsCheckBox.setObjectName("convertYieldsCheckBox")
        self.gridLayout.addWidget(self.convertYieldsCheckBox, 2, 4, 1, 1)
        self.urlLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.urlLineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlLineEdit.sizePolicy().hasHeightForWidth())
        self.urlLineEdit.setSizePolicy(sizePolicy)
        self.urlLineEdit.setReadOnly(False)
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.gridLayout.addWidget(self.urlLineEdit, 9, 2, 1, 3)
        self.yieldsLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.yieldsLabel.setObjectName("yieldsLabel")
        self.gridLayout.addWidget(self.yieldsLabel, 2, 1, 1, 1)
        self.imageRatingLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.imageRatingLabel.setText("")
        self.imageRatingLabel.setPixmap(QtGui.QPixmap(":/icons/star.png"))
        self.imageRatingLabel.setObjectName("imageRatingLabel")
        self.gridLayout.addWidget(self.imageRatingLabel, 1, 0, 1, 1)
        self.preparationTimeLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.preparationTimeLabel.setObjectName("preparationTimeLabel")
        self.gridLayout.addWidget(self.preparationTimeLabel, 5, 1, 1, 1)
        self.authorLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.authorLabel.setObjectName("authorLabel")
        self.gridLayout.addWidget(self.authorLabel, 4, 1, 1, 1)
        self.imageCuisineLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.imageCuisineLabel.setText("")
        self.imageCuisineLabel.setPixmap(QtGui.QPixmap(":/icons/cutleries.png"))
        self.imageCuisineLabel.setObjectName("imageCuisineLabel")
        self.gridLayout.addWidget(self.imageCuisineLabel, 3, 0, 1, 1)
        self.categoriesLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.categoriesLineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoriesLineEdit.sizePolicy().hasHeightForWidth())
        self.categoriesLineEdit.setSizePolicy(sizePolicy)
        self.categoriesLineEdit.setReadOnly(True)
        self.categoriesLineEdit.setObjectName("categoriesLineEdit")
        self.gridLayout.addWidget(self.categoriesLineEdit, 0, 2, 1, 3)
        self.cuisineComboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.cuisineComboBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cuisineComboBox.sizePolicy().hasHeightForWidth())
        self.cuisineComboBox.setSizePolicy(sizePolicy)
        self.cuisineComboBox.setEditable(True)
        self.cuisineComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cuisineComboBox.setObjectName("cuisineComboBox")
        self.gridLayout.addWidget(self.cuisineComboBox, 3, 2, 1, 3)
        self.imageLastCookedLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.imageLastCookedLabel.setText("")
        self.imageLastCookedLabel.setPixmap(QtGui.QPixmap(":/icons/calendar-day.png"))
        self.imageLastCookedLabel.setObjectName("imageLastCookedLabel")
        self.gridLayout.addWidget(self.imageLastCookedLabel, 8, 0, 1, 1)
        self.imageCategoriesLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.imageCategoriesLabel.setText("")
        self.imageCategoriesLabel.setPixmap(QtGui.QPixmap(":/icons/bread.png"))
        self.imageCategoriesLabel.setObjectName("imageCategoriesLabel")
        self.gridLayout.addWidget(self.imageCategoriesLabel, 0, 0, 1, 1)
        self.totalTimeLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.totalTimeLabel.setObjectName("totalTimeLabel")
        self.gridLayout.addWidget(self.totalTimeLabel, 7, 1, 1, 1)
        self.yieldsComboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.yieldsComboBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yieldsComboBox.sizePolicy().hasHeightForWidth())
        self.yieldsComboBox.setSizePolicy(sizePolicy)
        self.yieldsComboBox.setEditable(True)
        self.yieldsComboBox.setCurrentText("")
        self.yieldsComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.yieldsComboBox.setObjectName("yieldsComboBox")
        self.gridLayout.addWidget(self.yieldsComboBox, 2, 3, 1, 1)
        self.urlButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.urlButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/external.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.urlButton.setIcon(icon3)
        self.urlButton.setObjectName("urlButton")
        self.gridLayout.addWidget(self.urlButton, 9, 0, 1, 2)
        self.imageAuthorLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.imageAuthorLabel.setText("")
        self.imageAuthorLabel.setPixmap(QtGui.QPixmap(":/icons/quill.png"))
        self.imageAuthorLabel.setObjectName("imageAuthorLabel")
        self.gridLayout.addWidget(self.imageAuthorLabel, 4, 0, 1, 1)
        self.imageTotalTimeLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.imageTotalTimeLabel.setText("")
        self.imageTotalTimeLabel.setPixmap(QtGui.QPixmap(":/icons/clock.png"))
        self.imageTotalTimeLabel.setObjectName("imageTotalTimeLabel")
        self.gridLayout.addWidget(self.imageTotalTimeLabel, 7, 0, 1, 1)
        self.authorComboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.authorComboBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorComboBox.sizePolicy().hasHeightForWidth())
        self.authorComboBox.setSizePolicy(sizePolicy)
        self.authorComboBox.setEditable(True)
        self.authorComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.authorComboBox.setObjectName("authorComboBox")
        self.gridLayout.addWidget(self.authorComboBox, 4, 2, 1, 3)
        self.ratingSpinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.ratingSpinBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ratingSpinBox.sizePolicy().hasHeightForWidth())
        self.ratingSpinBox.setSizePolicy(sizePolicy)
        self.ratingSpinBox.setReadOnly(False)
        self.ratingSpinBox.setSuffix("/10")
        self.ratingSpinBox.setMinimum(-1)
        self.ratingSpinBox.setMaximum(10)
        self.ratingSpinBox.setProperty("value", -1)
        self.ratingSpinBox.setObjectName("ratingSpinBox")
        self.gridLayout.addWidget(self.ratingSpinBox, 1, 2, 1, 3)
        self.preparationStackedWidget = QtWidgets.QStackedWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preparationStackedWidget.sizePolicy().hasHeightForWidth())
        self.preparationStackedWidget.setSizePolicy(sizePolicy)
        self.preparationStackedWidget.setObjectName("preparationStackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.preparationTimeLineEdit = QtWidgets.QLineEdit(self.page)
        self.preparationTimeLineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preparationTimeLineEdit.sizePolicy().hasHeightForWidth())
        self.preparationTimeLineEdit.setSizePolicy(sizePolicy)
        self.preparationTimeLineEdit.setReadOnly(True)
        self.preparationTimeLineEdit.setObjectName("preparationTimeLineEdit")
        self.verticalLayout.addWidget(self.preparationTimeLineEdit)
        self.preparationStackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.preparationTimeEditor = TimeEditor(self.page_2)
        self.preparationTimeEditor.setObjectName("preparationTimeEditor")
        self.verticalLayout_2.addWidget(self.preparationTimeEditor)
        self.preparationStackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.preparationStackedWidget, 5, 2, 1, 3)
        self.cookingStackedWidget = QtWidgets.QStackedWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cookingStackedWidget.sizePolicy().hasHeightForWidth())
        self.cookingStackedWidget.setSizePolicy(sizePolicy)
        self.cookingStackedWidget.setObjectName("cookingStackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.cookingTimeLineEdit = QtWidgets.QLineEdit(self.page_3)
        self.cookingTimeLineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cookingTimeLineEdit.sizePolicy().hasHeightForWidth())
        self.cookingTimeLineEdit.setSizePolicy(sizePolicy)
        self.cookingTimeLineEdit.setReadOnly(True)
        self.cookingTimeLineEdit.setObjectName("cookingTimeLineEdit")
        self.verticalLayout_13.addWidget(self.cookingTimeLineEdit)
        self.cookingStackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.cookingTimeEditor = TimeEditor(self.page_4)
        self.cookingTimeEditor.setObjectName("cookingTimeEditor")
        self.verticalLayout_14.addWidget(self.cookingTimeEditor)
        self.cookingStackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.cookingStackedWidget, 6, 2, 1, 3)
        self.totalTimeStackedWidget = QtWidgets.QStackedWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalTimeStackedWidget.sizePolicy().hasHeightForWidth())
        self.totalTimeStackedWidget.setSizePolicy(sizePolicy)
        self.totalTimeStackedWidget.setObjectName("totalTimeStackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.totalTimeLineEdit = QtWidgets.QLineEdit(self.page_5)
        self.totalTimeLineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalTimeLineEdit.sizePolicy().hasHeightForWidth())
        self.totalTimeLineEdit.setSizePolicy(sizePolicy)
        self.totalTimeLineEdit.setReadOnly(True)
        self.totalTimeLineEdit.setObjectName("totalTimeLineEdit")
        self.verticalLayout_15.addWidget(self.totalTimeLineEdit)
        self.totalTimeStackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.totalTimeEditor = TimeEditor(self.page_6)
        self.totalTimeEditor.setObjectName("totalTimeEditor")
        self.verticalLayout_16.addWidget(self.totalTimeEditor)
        self.totalTimeStackedWidget.addWidget(self.page_6)
        self.gridLayout.addWidget(self.totalTimeStackedWidget, 7, 2, 1, 3)
        self.verticalLayout_3.addWidget(self.imageSplitter)
        self.mainTabWidget.addTab(self.mainTab, "")
        self.instructionsTab = QtWidgets.QWidget()
        self.instructionsTab.setObjectName("instructionsTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.instructionsTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textViewSplitter = QtWidgets.QSplitter(self.instructionsTab)
        self.textViewSplitter.setOrientation(QtCore.Qt.Vertical)
        self.textViewSplitter.setOpaqueResize(False)
        self.textViewSplitter.setHandleWidth(2)
        self.textViewSplitter.setObjectName("textViewSplitter")
        self.descriptionGroupBox = QtWidgets.QGroupBox(self.textViewSplitter)
        self.descriptionGroupBox.setCheckable(False)
        self.descriptionGroupBox.setChecked(False)
        self.descriptionGroupBox.setObjectName("descriptionGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.descriptionGroupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.descriptionStackedWidget = QtWidgets.QStackedWidget(self.descriptionGroupBox)
        self.descriptionStackedWidget.setObjectName("descriptionStackedWidget")
        self.descriptionPagePlain = QtWidgets.QWidget()
        self.descriptionPagePlain.setObjectName("descriptionPagePlain")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.descriptionPagePlain)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.descriptionPlainTextEdit = QtWidgets.QPlainTextEdit(self.descriptionPagePlain)
        self.descriptionPlainTextEdit.setObjectName("descriptionPlainTextEdit")
        self.horizontalLayout_2.addWidget(self.descriptionPlainTextEdit)
        self.descriptionStackedWidget.addWidget(self.descriptionPagePlain)
        self.descriptionPageMarkdown = QtWidgets.QWidget()
        self.descriptionPageMarkdown.setObjectName("descriptionPageMarkdown")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.descriptionPageMarkdown)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.descriptionMarkDownTextEdit = QtWidgets.QTextEdit(self.descriptionPageMarkdown)
        self.descriptionMarkDownTextEdit.setReadOnly(True)
        self.descriptionMarkDownTextEdit.setObjectName("descriptionMarkDownTextEdit")
        self.verticalLayout_8.addWidget(self.descriptionMarkDownTextEdit)
        self.descriptionStackedWidget.addWidget(self.descriptionPageMarkdown)
        self.horizontalLayout_3.addWidget(self.descriptionStackedWidget)
        self.instructionsGroupBox = QtWidgets.QGroupBox(self.textViewSplitter)
        self.instructionsGroupBox.setCheckable(False)
        self.instructionsGroupBox.setChecked(False)
        self.instructionsGroupBox.setObjectName("instructionsGroupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.instructionsGroupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.instructionsStackedWidget = QtWidgets.QStackedWidget(self.instructionsGroupBox)
        self.instructionsStackedWidget.setObjectName("instructionsStackedWidget")
        self.instructionPagePlain = QtWidgets.QWidget()
        self.instructionPagePlain.setObjectName("instructionPagePlain")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.instructionPagePlain)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.instructionsPlainTextEdit = QtWidgets.QPlainTextEdit(self.instructionPagePlain)
        self.instructionsPlainTextEdit.setPlaceholderText("Instructions")
        self.instructionsPlainTextEdit.setObjectName("instructionsPlainTextEdit")
        self.verticalLayout_9.addWidget(self.instructionsPlainTextEdit)
        self.instructionsStackedWidget.addWidget(self.instructionPagePlain)
        self.instructionsPageMarkdown = QtWidgets.QWidget()
        self.instructionsPageMarkdown.setObjectName("instructionsPageMarkdown")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.instructionsPageMarkdown)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.instructionsMarkdownTextEdit = QtWidgets.QTextEdit(self.instructionsPageMarkdown)
        self.instructionsMarkdownTextEdit.setReadOnly(True)
        self.instructionsMarkdownTextEdit.setObjectName("instructionsMarkdownTextEdit")
        self.verticalLayout_10.addWidget(self.instructionsMarkdownTextEdit)
        self.instructionsStackedWidget.addWidget(self.instructionsPageMarkdown)
        self.verticalLayout_7.addWidget(self.instructionsStackedWidget)
        self.notesGroupBox = QtWidgets.QGroupBox(self.textViewSplitter)
        self.notesGroupBox.setCheckable(False)
        self.notesGroupBox.setChecked(False)
        self.notesGroupBox.setObjectName("notesGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.notesGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.notesStackedWidget = QtWidgets.QStackedWidget(self.notesGroupBox)
        self.notesStackedWidget.setObjectName("notesStackedWidget")
        self.notesPagePlain = QtWidgets.QWidget()
        self.notesPagePlain.setObjectName("notesPagePlain")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.notesPagePlain)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.notesPlainTextEdit = QtWidgets.QPlainTextEdit(self.notesPagePlain)
        self.notesPlainTextEdit.setObjectName("notesPlainTextEdit")
        self.verticalLayout_11.addWidget(self.notesPlainTextEdit)
        self.notesStackedWidget.addWidget(self.notesPagePlain)
        self.notesPageMarkdown = QtWidgets.QWidget()
        self.notesPageMarkdown.setObjectName("notesPageMarkdown")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.notesPageMarkdown)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.notesMarkdownTextEdit = QtWidgets.QTextEdit(self.notesPageMarkdown)
        self.notesMarkdownTextEdit.setReadOnly(True)
        self.notesMarkdownTextEdit.setObjectName("notesMarkdownTextEdit")
        self.verticalLayout_12.addWidget(self.notesMarkdownTextEdit)
        self.notesStackedWidget.addWidget(self.notesPageMarkdown)
        self.verticalLayout_4.addWidget(self.notesStackedWidget)
        self.verticalLayout_6.addWidget(self.textViewSplitter)
        self.mainTabWidget.addTab(self.instructionsTab, "")
        self.layoutWidget2 = QtWidgets.QWidget(self.mainSplitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.ingredientLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.ingredientLayout.setContentsMargins(0, 0, 0, 0)
        self.ingredientLayout.setObjectName("ingredientLayout")
        self.ingredientRowLayout = QtWidgets.QHBoxLayout()
        self.ingredientRowLayout.setObjectName("ingredientRowLayout")
        self.newIngredientAmountEditor = AmountEditor(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newIngredientAmountEditor.sizePolicy().hasHeightForWidth())
        self.newIngredientAmountEditor.setSizePolicy(sizePolicy)
        self.newIngredientAmountEditor.setMinimumSize(QtCore.QSize(200, 0))
        self.newIngredientAmountEditor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.newIngredientAmountEditor.setObjectName("newIngredientAmountEditor")
        self.ingredientRowLayout.addWidget(self.newIngredientAmountEditor)
        self.newIngredientLineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newIngredientLineEdit.sizePolicy().hasHeightForWidth())
        self.newIngredientLineEdit.setSizePolicy(sizePolicy)
        self.newIngredientLineEdit.setObjectName("newIngredientLineEdit")
        self.ingredientRowLayout.addWidget(self.newIngredientLineEdit)
        self.ingredientLayout.addLayout(self.ingredientRowLayout)
        self.ingredientButtonLayout = QtWidgets.QHBoxLayout()
        self.ingredientButtonLayout.setObjectName("ingredientButtonLayout")
        self.addNewIngredientButton = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addNewIngredientButton.sizePolicy().hasHeightForWidth())
        self.addNewIngredientButton.setSizePolicy(sizePolicy)
        self.addNewIngredientButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addNewIngredientButton.setIcon(icon1)
        self.addNewIngredientButton.setObjectName("addNewIngredientButton")
        self.ingredientButtonLayout.addWidget(self.addNewIngredientButton)
        self.optionalCheckbox = QtWidgets.QCheckBox(self.layoutWidget2)
        self.optionalCheckbox.setEnabled(False)
        self.optionalCheckbox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.optionalCheckbox.setObjectName("optionalCheckbox")
        self.ingredientButtonLayout.addWidget(self.optionalCheckbox)
        self.isGroupCheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        self.isGroupCheckBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isGroupCheckBox.sizePolicy().hasHeightForWidth())
        self.isGroupCheckBox.setSizePolicy(sizePolicy)
        self.isGroupCheckBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.isGroupCheckBox.setObjectName("isGroupCheckBox")
        self.ingredientButtonLayout.addWidget(self.isGroupCheckBox)
        self.alternativeCheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        self.alternativeCheckBox.setEnabled(False)
        self.alternativeCheckBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.alternativeCheckBox.setText("")
        self.alternativeCheckBox.setObjectName("alternativeCheckBox")
        self.ingredientButtonLayout.addWidget(self.alternativeCheckBox)
        self.ingredientLayout.addLayout(self.ingredientButtonLayout)
        self.ingredientTreeView = DraggingTreeView(self.layoutWidget2)
        self.ingredientTreeView.setAcceptDrops(True)
        self.ingredientTreeView.setDragEnabled(True)
        self.ingredientTreeView.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.ingredientTreeView.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.ingredientTreeView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ingredientTreeView.setItemsExpandable(True)
        self.ingredientTreeView.setAnimated(False)
        self.ingredientTreeView.setWordWrap(True)
        self.ingredientTreeView.setObjectName("ingredientTreeView")
        self.ingredientLayout.addWidget(self.ingredientTreeView)
        self.deleteIngredientsButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.deleteIngredientsButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteIngredientsButton.sizePolicy().hasHeightForWidth())
        self.deleteIngredientsButton.setSizePolicy(sizePolicy)
        self.deleteIngredientsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.deleteIngredientsButton.setIcon(icon2)
        self.deleteIngredientsButton.setObjectName("deleteIngredientsButton")
        self.ingredientLayout.addWidget(self.deleteIngredientsButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.mainSplitter)
        RecipeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RecipeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 30))
        self.menubar.setObjectName("menubar")
        self.menuRecipe = QtWidgets.QMenu(self.menubar)
        self.menuRecipe.setObjectName("menuRecipe")
        RecipeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RecipeWindow)
        self.statusbar.setObjectName("statusbar")
        RecipeWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(RecipeWindow)
        self.toolBar.setObjectName("toolBar")
        RecipeWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave = QtWidgets.QAction(RecipeWindow)
        self.actionSave.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon4)
        self.actionSave.setObjectName("actionSave")
        self.actionRevert = QtWidgets.QAction(RecipeWindow)
        self.actionRevert.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/arrow-return-180-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRevert.setIcon(icon5)
        self.actionRevert.setObjectName("actionRevert")
        self.actionEdit = QtWidgets.QAction(RecipeWindow)
        self.actionEdit.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/lock-unlock.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionEdit.setIcon(icon6)
        self.actionEdit.setObjectName("actionEdit")
        self.actionNew_Category = QtWidgets.QAction(RecipeWindow)
        self.actionNew_Category.setIcon(icon1)
        self.actionNew_Category.setObjectName("actionNew_Category")
        self.actionDelete_Ingredients = QtWidgets.QAction(RecipeWindow)
        self.actionDelete_Ingredients.setIcon(icon2)
        self.actionDelete_Ingredients.setObjectName("actionDelete_Ingredients")
        self.actionDelete_Image_s = QtWidgets.QAction(RecipeWindow)
        self.actionDelete_Image_s.setIcon(icon2)
        self.actionDelete_Image_s.setObjectName("actionDelete_Image_s")
        self.actionAdd_Image_s = QtWidgets.QAction(RecipeWindow)
        self.actionAdd_Image_s.setIcon(icon1)
        self.actionAdd_Image_s.setObjectName("actionAdd_Image_s")
        self.menuRecipe.addAction(self.actionEdit)
        self.menuRecipe.addAction(self.actionSave)
        self.menuRecipe.addAction(self.actionRevert)
        self.menubar.addAction(self.menuRecipe.menuAction())
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionRevert)
        self.toolBar.addSeparator()

        self.retranslateUi(RecipeWindow)
        self.mainTabWidget.setCurrentIndex(0)
        self.preparationStackedWidget.setCurrentIndex(0)
        self.cookingStackedWidget.setCurrentIndex(0)
        self.totalTimeStackedWidget.setCurrentIndex(0)
        self.descriptionStackedWidget.setCurrentIndex(1)
        self.instructionsStackedWidget.setCurrentIndex(1)
        self.notesStackedWidget.setCurrentIndex(1)
        self.newIngredientLineEdit.returnPressed.connect(self.addNewIngredientButton.click)
        QtCore.QMetaObject.connectSlotsByName(RecipeWindow)
        RecipeWindow.setTabOrder(self.recipeTitleLineEdit, self.calculateAmountDoubleSpinBox)
        RecipeWindow.setTabOrder(self.calculateAmountDoubleSpinBox, self.mainTabWidget)
        RecipeWindow.setTabOrder(self.mainTabWidget, self.categoriesLineEdit)
        RecipeWindow.setTabOrder(self.categoriesLineEdit, self.ratingSpinBox)
        RecipeWindow.setTabOrder(self.ratingSpinBox, self.yieldsDoubleSpinBox)
        RecipeWindow.setTabOrder(self.yieldsDoubleSpinBox, self.yieldsComboBox)
        RecipeWindow.setTabOrder(self.yieldsComboBox, self.convertYieldsCheckBox)
        RecipeWindow.setTabOrder(self.convertYieldsCheckBox, self.cuisineComboBox)
        RecipeWindow.setTabOrder(self.cuisineComboBox, self.authorComboBox)
        RecipeWindow.setTabOrder(self.authorComboBox, self.lastCookedDateEdit)
        RecipeWindow.setTabOrder(self.lastCookedDateEdit, self.neverCookedCheckBox)
        RecipeWindow.setTabOrder(self.neverCookedCheckBox, self.urlLineEdit)
        RecipeWindow.setTabOrder(self.urlLineEdit, self.newIngredientAmountEditor)
        RecipeWindow.setTabOrder(self.newIngredientAmountEditor, self.newIngredientLineEdit)
        RecipeWindow.setTabOrder(self.newIngredientLineEdit, self.ingredientTreeView)

    def retranslateUi(self, RecipeWindow):
        _translate = QtCore.QCoreApplication.translate
        self.recipeTitleLabel.setText(_translate("RecipeWindow", "Title"))
        self.recipeTitleLineEdit.setPlaceholderText(_translate("RecipeWindow", "Title"))
        self.calculateAmountDoubleSpinBox.setPrefix(_translate("RecipeWindow", "Calculate amount for: "))
        self.addImagesButton.setText(_translate("RecipeWindow", "Add Image(s)"))
        self.deleteImagesButton.setText(_translate("RecipeWindow", "Delete Image(s)"))
        self.lastCookedDateEdit.setDisplayFormat(_translate("RecipeWindow", "yyyy-MM-dd"))
        self.neverCookedCheckBox.setText(_translate("RecipeWindow", "Never"))
        self.catgoriesButton.setText(_translate("RecipeWindow", "Categories:"))
        self.cuisineLabel.setText(_translate("RecipeWindow", "Cuisine:"))
        self.lastCookedLabel.setText(_translate("RecipeWindow", "Last Cooked:"))
        self.ratingLabel.setText(_translate("RecipeWindow", "Rating:"))
        self.cookingTimeLabel.setText(_translate("RecipeWindow", "Cooking:"))
        self.convertYieldsCheckBox.setText(_translate("RecipeWindow", "Convert"))
        self.urlLineEdit.setPlaceholderText(_translate("RecipeWindow", "URL of the Recipe"))
        self.yieldsLabel.setText(_translate("RecipeWindow", "Yields:"))
        self.preparationTimeLabel.setText(_translate("RecipeWindow", "Preparation:"))
        self.authorLabel.setText(_translate("RecipeWindow", "Author:"))
        self.categoriesLineEdit.setPlaceholderText(_translate("RecipeWindow", "Categories"))
        self.totalTimeLabel.setText(_translate("RecipeWindow", "Total:"))
        self.urlButton.setText(_translate("RecipeWindow", "URL:"))
        self.ratingSpinBox.setSpecialValueText(_translate("RecipeWindow", "unrated"))
        self.preparationTimeLineEdit.setPlaceholderText(_translate("RecipeWindow", "Preparation time"))
        self.cookingTimeLineEdit.setPlaceholderText(_translate("RecipeWindow", "Cooking Time"))
        self.totalTimeLineEdit.setPlaceholderText(_translate("RecipeWindow", "Total Time"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.mainTab), _translate("RecipeWindow", "Information"))
        self.descriptionGroupBox.setTitle(_translate("RecipeWindow", "Description"))
        self.descriptionPlainTextEdit.setPlaceholderText(_translate("RecipeWindow", "Description"))
        self.descriptionMarkDownTextEdit.setPlaceholderText(_translate("RecipeWindow", "Description"))
        self.instructionsGroupBox.setTitle(_translate("RecipeWindow", "Instructions"))
        self.instructionsMarkdownTextEdit.setPlaceholderText(_translate("RecipeWindow", "Instructions"))
        self.notesGroupBox.setTitle(_translate("RecipeWindow", "Notes"))
        self.notesPlainTextEdit.setPlaceholderText(_translate("RecipeWindow", "Own notes/comments"))
        self.notesMarkdownTextEdit.setPlaceholderText(_translate("RecipeWindow", "Own notes/comments"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.instructionsTab), _translate("RecipeWindow", "Instructions"))
        self.newIngredientLineEdit.setPlaceholderText(_translate("RecipeWindow", "Ingredient"))
        self.addNewIngredientButton.setText(_translate("RecipeWindow", "Add Ingredient"))
        self.optionalCheckbox.setText(_translate("RecipeWindow", "Optional"))
        self.isGroupCheckBox.setText(_translate("RecipeWindow", "Is Group"))
        self.deleteIngredientsButton.setText(_translate("RecipeWindow", "Delete Ingredient(s)"))
        self.menuRecipe.setTitle(_translate("RecipeWindow", "Recipe"))
        self.toolBar.setWindowTitle(_translate("RecipeWindow", "toolBar"))
        self.actionSave.setText(_translate("RecipeWindow", "Save"))
        self.actionRevert.setText(_translate("RecipeWindow", "Revert"))
        self.actionEdit.setText(_translate("RecipeWindow", "Edit"))
        self.actionNew_Category.setText(_translate("RecipeWindow", "New Category..."))
        self.actionDelete_Ingredients.setText(_translate("RecipeWindow", "Delete Ingredients"))
        self.actionDelete_Ingredients.setToolTip(_translate("RecipeWindow", "Delete Ingredient(s)"))
        self.actionDelete_Image_s.setText(_translate("RecipeWindow", "Delete Image(s)"))
        self.actionAdd_Image_s.setText(_translate("RecipeWindow", "Add Image(s)"))
from qisit.qt.recipewindow.amounteditor import AmountEditor
from qisit.qt.recipewindow.draggingtreeview import DraggingTreeView
from qisit.qt.recipewindow.timeeditor import TimeEditor
from qisit.qt.resources import resources_rc
